export const styles = {
  root: {
    minHeight: "100vh",
    background:
      "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(74, 158, 255, 0.12), transparent), #0b0d12",
    color: "#e8eaf0",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
  },
  card: {
    background: "linear-gradient(180deg, #1c2030 0%, #161a26 100%)",
    border: "1px solid #2f3548",
    borderRadius: "16px",
    padding: "40px",
    width: "100%",
    maxWidth: "420px",
    boxShadow: "0 16px 48px rgba(0, 0, 0, 0.45)",
  },
  logo: {
    fontSize: "11px",
    letterSpacing: "0.18em",
    color: "#60a5fa",
    textTransform: "uppercase",
    marginBottom: "8px",
    fontWeight: "600",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    marginBottom: "32px",
    color: "#ffffff",
    letterSpacing: "-0.02em",
  },
  tabs: {
    display: "flex",
    gap: "4px",
    marginBottom: "28px",
    background: "#0f1117",
    borderRadius: "8px",
    padding: "4px",
  },
  tab: (active) => ({
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontFamily: "inherit",
    fontWeight: "600",
    letterSpacing: "0.05em",
    transition: "all 0.2s",
    background: active ? "#4a9eff" : "transparent",
    color: active ? "#ffffff" : "#6b7280",
  }),
  field: {
    marginBottom: "16px",
  },
  label: {
    display: "block",
    fontSize: "11px",
    letterSpacing: "0.1em",
    color: "#6b7280",
    textTransform: "uppercase",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    background: "#0f1117",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    color: "#e8eaf0",
    fontSize: "14px",
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.2s",
  },
  btn: (variant = "primary") => ({
    width: "100%",
    padding: "12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontFamily: "inherit",
    fontWeight: "700",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    marginTop: "8px",
    transition: "all 0.2s",
    background: variant === "primary" ? "#4a9eff" : "#1a1d27",
    color: variant === "primary" ? "#ffffff" : "#4a9eff",
    border: variant === "secondary" ? "1px solid #4a9eff" : "none",
  }),
  error: {
    background: "#2a1a1a",
    border: "1px solid #ff4a4a",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "12px",
    color: "#ff6b6b",
    marginTop: "12px",
  },
  success: {
    background: "#1a2a1a",
    border: "1px solid #4aff7a",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "12px",
    color: "#4aff7a",
    marginTop: "12px",
  },
  dashboard: {
    width: "100%",
    maxWidth: "720px",
  },
  dashboardCard: {
    background: "linear-gradient(180deg, #1c2030 0%, #161a26 100%)",
    border: "1px solid #2f3548",
    borderRadius: "16px",
    padding: "32px 36px",
    width: "100%",
    maxWidth: "720px",
    boxShadow: "0 16px 48px rgba(0, 0, 0, 0.45)",
  },
  dashHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
  },
  badge: {
    background: "#1a2a1a",
    border: "1px solid #4aff7a",
    borderRadius: "20px",
    padding: "4px 12px",
    fontSize: "11px",
    color: "#4aff7a",
    letterSpacing: "0.1em",
  },
  infoRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 0",
    borderBottom: "1px solid #2a2d3a",
    fontSize: "13px",
  },
  infoKey: { color: "#6b7280", letterSpacing: "0.05em" },
  infoVal: { color: "#e8eaf0", fontWeight: "600" },
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    marginTop: "24px",
  },
  actionBtn: (color) => ({
    padding: "16px",
    border: `1px solid ${color}22`,
    borderRadius: "8px",
    background: `${color}11`,
    color: color,
    cursor: "pointer",
    fontSize: "12px",
    fontFamily: "inherit",
    fontWeight: "700",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    transition: "all 0.2s",
  }),
  logoutBtn: {
    padding: "8px 16px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "transparent",
    color: "#6b7280",
    cursor: "pointer",
    fontSize: "12px",
    fontFamily: "inherit",
    letterSpacing: "0.05em",
  },
};